### ISSUE TITLE
Setup with docker-compose

### ISSUE THREAD

**Issue by loehra** [jazzdd86/phpVirtualbox#10]
Hi!
I am trying to setup the vboxwebsrv contaier and phpvirtualbox container using docker-compose. I am stuck with translating 
 --link vbox_websrv_1:MyComputer 
from the vboxwebsrv run instructions to docker-compose yml, I am always getting 
Error: No vboxwebsrv instance linked? Use "--link containername:myname"

What does ->MyComputer<- mean, respectively, what does ->myname<- mean?
Thanks!

This is my docker-compose:
```
version: '2'
services:
  phpvirtualbox:
    image: jazzdd/phpvirtualbox
    container_name: phpvirtualbox
    ports:
      - "80:80"
    environment:
      - CONF_browserRestrictFolders=/home/encrypted/vm/iso
    links:
      - phpvirtualbox-vboxwebsrv
    depends_on:
      - phpvirtualbox-vboxwebsrv


  phpvirtualbox-vboxwebsrv:
    image: jazzdd/vboxwebsrv
    container_name: phpvirtualbox-vboxwebsrv
    environment:
      - USE_KEY=1
    volumes:
       - /home/encrypted/docker/phpvirtualbox/ssh-vboxwebsrv:/root/.ssh
    command: vm@xx.yy.zz.uu
 ```

**Comment by jazzdd86** [comment]
Hi,
I stumbled over this issue a few weeks ago, as I started using virtualbox and phpvirtualbox after 2 years not using it.

The use of "links:" is depricated, so I have to look into the whole configuration script and edit it the way it works again.

As workaround I use the direct conection to the vboxwebsrv as vboxwebsrv and phpvbox are in the same local network - meens the vboxwebsrv container starts the vboxwebsrv on the host machine and I am letting phpvbox connecting to that port (5678).

The myComputer or name is the display name used in the phpvbox UI to display the VBOX Server.

long story short, this works for me at this time:
```yml
version: '3'
services:
    vbox_http:
        container_name: vbox_http
        restart: always
        ports:
            - "80:80"
        environment: 
            ID_PORT_18083_TCP: "vboxwebsrvHostNameOrIP:5678"
            ID_NAME: "Name" #display name
            ID_USER: "vm" #vboxwebsrv user
            ID_PW: "secret" #vboxwebsrv pw
            CONF_browserRestrictFolders: "/data,/home,/usr/lib/virtualbox/"
        depends_on:
            - vbox_websrv
        image: jazzdd/phpvirtualbox

    vbox_websrv:
        container_name: vbox_websrv
        restart: always
        volumes:
            - "./ssh:/root/.ssh"
        environment:
            USE_KEY: 1
        image: jazzdd/vboxwebsrv
        command: secret@vboxwebsrvHostNameOrIP
```

Its in my todo for next few weeks, I will post here any updates
